"""table users information

Revision ID: 0fa747e970a7
Revises: 0349a9ebafa2
Create Date: 2024-12-30 10:57:59.634653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa747e970a7'
down_revision = '0349a9ebafa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_USER_INFO',
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dietary_preferences', sa.String(), nullable=True),
    sa.Column('meals_per_day', sa.String(), nullable=True),
    sa.Column('deit_description', sa.String(), nullable=True),
    sa.Column('activity_levels', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['TBL_APP_USERS.user_id'], name=op.f('fk_TBL_USER_INFO_user_id_TBL_APP_USERS')),
    sa.PrimaryKeyConstraint('info_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBL_USER_INFO')
    # ### end Alembic commands ###
